AWSTemplateFormatVersion: "2010-09-09"
Description: Create an ALB in the Default VPC

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  SubnetIds:
    Type: CommaDelimitedList
    Description: List of Subnet IDs within the VPC

Resources:
  nginxappALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: nginxappALB
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      Type: application
      Tags:
        - Key: Name
          Value: nginxappALB

  nginxappTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: nginxappTargetGroup
      Port: 8080
      Protocol: HTTP
      TargetType: instance
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: nginxappTG

  nginxappListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref nginxappALB
      Port: 8080
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref nginxappTargetGroup

Outputs:
  AlbDnsName:
    Value: !GetAtt nginxappALB.DNSName
