AWSTemplateFormatVersion: "2010-09-09"
Description: Create an NLB in the Default VPC

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  SubnetIds:
    Type: CommaDelimitedList
    Description: List of Subnet IDs within the VPC

Resources:
  nginxappNLB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: nginxappNLB
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      Type: application
      Tags:
        - Key: Name
          Value: nginxappNLB
      SecurityGroups:
        - !Ref nginxappSecurityGroup

  nginxappTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: nginxappTargetGroup
      Port: 8080
      Protocol: HTTP
      TargetType: instance
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: nginxappTG

  nginxappListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref nginxappNLB
      Port: 8080
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref nginxappTargetGroup

  nginxappSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Security group for the nginxappNLB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: nginxappSecurityGroup

Outputs:
  NLBDNSName:
    Value: !GetAtt nginxappNLB.DNSName
