---
  - name: Install dependencies
    become: yes
    apt:
      pkg:
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - software-properties-common
        - nginx
      state: latest
      update_cache: true
    
  - name: Install Docker
    become: yes
    shell : |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        apt-cache policy docker-ce
        apt install docker-ce -y
        usermod -aG docker ubuntu
        exit

  - name: Install Kubernetes
    become: yes
    shell : |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
        mkdir -p /usr/local/bin/
        install minikube /usr/local/bin/
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl


  - name: Start Kubernetes
    become: no
    shell : |
        minikube start
  
  - name: Run app
    become: no
    shell : |
        dockerpath=dimension90/nginxapp
        kubectl create deployment nginxapp-minikube --image=$dockerpath:latest

  - name: Copy service config
    become: no
    copy:
      src: files/service.yml
      dest: /home/ubuntu
    tags:
      - simple_copy

  - name: Copy proxy nginx config
    become: yes
    copy:
      src: files/default.conf
      dest: /etc/nginx/conf.d
    tags:
      - simple_copy
  
  - name: Deploy service
    become: no
    shell : |
        kubectl apply -f service.yml

  - name: Nginx restart
    become: yes
    shell : |
        service nginx restart
    