Description: >
  Nginxapp stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
  VpcId:
    Description: ID of the VPC.
    Type: AWS::EC2::VPC::Id

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub nginxapp-${ID}
      GroupDescription: Allow port 22 and port 8080.
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0


  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      VpcId: !Ref VpcId
      InstanceType: t2.medium
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: nginxapp # If you use another key pair name, you should change this value to match.
      # If this ami id is not available for you, you can find another (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html)
      # Ubuntu 18 or higher works fine
      ImageId: ami-068663a3c619dd892 
      Tags:
        - Key: Name
          Value: !Sub server-${ID}