apiVersion: v1
kind: Service
metadata:
  name: nginxapp-minikube
  labels:
    app: nginxapp-minikube
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  selector:
    app: nginxapp-minikube
